project:
  name: Ozon Code Platform Template API
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 5002
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

gateway:
  host: 0.0.0.0
  port: 5003
  allowedCorsOrigins:
    - "http://localhost:5001"
    - "http://0.0.0.0:5001"
    - "http://127.0.0.1:5001"

swagger:
  host: 0.0.0.0
  port: 5001
  filepath: "swagger/api/category-service/category-service.swagger.json"
